title: Rafael Correia
description: My Personal Blog
author: Rafael Correia
logo: "https://secure.gravatar.com/avatar/2731c601d40345f7afb9027e41110312?size=64"
github: https://github.com/rafaeljpc
about: Game and Software developer

allowsearch: true

baseurl: ""
url: "https://rafaeljpc.github.io/"

share:
  twitter_username: rafaeljpc
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, kramdown]
